### ISSUE TITLE
pin to newest napari RC

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/brainrender-napari#35]
This would help fix the problem described in https://github.com/brainglobe/brainglobe-napari/pull/31#issuecomment-1611678666 (but would we then have to pin the entirety of brainglobe and is that a good idea?

**Comment by alessandrofelder** [comment]
Don't see a reason to try and convince you otherwise. BG packaging expert @willGraham01 may wish to chime in?

**Comment by willGraham01** [comment]
Only slight evil that springs to mind (to come out of the necessary "evil") is that even if there's one BG tool that breaks in say Napari `vX.2`, _all_ BG packages and our users will have to be stuck with the previous Napari `vX.1` until we fix the issue (since all BG packages go into one environment).

I think it'll be fine so long as we watch for new releases and potential breakages. And I don't image that a) there will be a lot of cases of this happening and b) we'll be negligent enough to _not_ fix "breaking" issues promptly if they did crop up.

**Comment by adamltyson** [comment]
I think that's ok TBH. One of the main motivations of moving to "BrainGlobe" and away from individual tools is to provide an integrated analysis environment that "just works".

**Comment by adamltyson** [comment]
I think we need to just make sure we keep up to date with new napari versions and fix issues as they crop up. Both @alessandrofelder and I have come up with issues in napari this week, and both issues were resolved in <24 hours by the core devs.

**Comment by alessandrofelder** [comment]
Sounds good to me!
